# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Flake8 syntax checker

on:
  push:
    branches: [ restructure ]
  pull_request:
    branches: [ restructure ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 2.7
      uses: actions/setup-python@v1
      with:
        python-version: 2.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # Download the config file
        wget https://raw.githubusercontent.com/tikk3r/lofar-highres-widefield/restructure/flake8_setup.cfg
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,E101,E111,E112,E113,E305,E713,E714,F63,F7,F82,W1 --show-source --statistics --config=flake8_setup.cfg
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics --config=flake8_setup.cfg
